/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StrobeManual2RouteImport } from './routes/strobe-manual-2'
import { Route as StrobeManualRouteImport } from './routes/strobe-manual'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StrobeManual2Route = StrobeManual2RouteImport.update({
  id: '/strobe-manual-2',
  path: '/strobe-manual-2',
  getParentRoute: () => rootRouteImport,
} as any)
const StrobeManualRoute = StrobeManualRouteImport.update({
  id: '/strobe-manual',
  path: '/strobe-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/strobe-manual': typeof StrobeManualRoute
  '/strobe-manual-2': typeof StrobeManual2Route
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/strobe-manual': typeof StrobeManualRoute
  '/strobe-manual-2': typeof StrobeManual2Route
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/strobe-manual': typeof StrobeManualRoute
  '/strobe-manual-2': typeof StrobeManual2Route
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/strobe-manual' | '/strobe-manual-2' | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/strobe-manual' | '/strobe-manual-2' | '/reset-password'
  id: '__root__' | '/' | '/strobe-manual' | '/strobe-manual-2' | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StrobeManualRoute: typeof StrobeManualRoute
  StrobeManual2Route: typeof StrobeManual2Route
  ResetPasswordRoute: typeof ResetPasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StrobeManualRoute: StrobeManualRoute,
  StrobeManual2Route: StrobeManual2Route,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
